displayName=Tile Filler
author=Wyrembelski
description=Fills tiles completely with a color and opacity of your choosing, like a solid version of tile markers
tags=tile,marker,ground,fill,color,overlay
plugins=com.tilefiller.TileFillerPlugin
version=
build=standard
